// src/app/modules/resume/elements/card.component.ts
import {Component} from '@angular/core';


@Component({
  selector: 'app-card',
  templateUrl: 'card.component.html'
})
export class CardComponent {
}

<div
  class="relative bg-white rounded-lg border border-gray-200 shadow-md ">

  <div class="flex flex-col gap-2 border-b border-b-gray-200 p-4 bg-gray-100">
    <div class="flex ">
      <div class="text-gray-700 font-bold">
        <ng-content select="[title]"></ng-content>
      </div>
    </div>
  </div>

  <div class="p-4 pb-6">
    <ng-content></ng-content>
  </div>

</div>

// src/components/Card.tsx
const Card = ({children, title}) => {
    return (
        <div
            className="relative bg-white rounded-lg ring-[1.5px] ring-gray-300 shadow-md overflow-hidden">
            <div className="flex flex-col gap-2 border-b border-b-gray-200 p-4 bg-gray-100 print:bg-gray-200">
                <div className="flex ">
                    <div className="text-gray-600 font-bold">
                        {title}
                    </div>
                </div>
            </div>

            <div className="p-4 pb-6">
                {children}
            </div>
        </div>
    )
}

export default Card;
