// src/components/SkillProgress.tsx
import {useMemo} from "react";
import {Level} from "../types";

const SkillProgress = ({level}) => {

    const width = useMemo(() => {
        switch (level) {
            case Level.beginner:
                return '25%';
            case Level.medium:
                return '50%';
            case Level.advance:
                return '75%';
            case Level.expert:
                return '100%';
        }
    }, [level])

    return (
        <div className="w-full bg-gray-200 rounded-full h-0.5">
            <div className="bg-blue-600 h-0.5 rounded-full" style={{width: width}}></div>
        </div>
    )
}

export default SkillProgress;

// src/app/modules/resume/elements/skill/skill.progress.component.ts
import {Component, OnInit, Input} from '@angular/core';
import {Level} from '../../_models/level';

@Component({
  selector: 'app-elements-skill-progress',
  templateUrl: './skill.progress.component.html',
  styleUrls: ['skill.progress.component.scss']
})
export class SkillProgressComponent implements OnInit {

  @Input() level: Level;

  constructor() {
  }

  get Level(): any {
    return Level;
  }

  ngOnInit(): void {
  }

  getWidth(): string {
    switch (this.level) {
      case Level.beginner:
        return '25%';
      case Level.medium:
        return '50%';
      case Level.advance:
        return '75%';
      case Level.expert:
        return '100%';
    }
  }
}

<div class="w-full bg-gray-200 rounded-full h-0.5">
  <div class="bg-blue-600 h-0.5 rounded-full" [style.width]="getWidth()"></div>
</div>
